package dao;// default package
// Generated Mar 20, 2021, 11:48:12 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuyerBuyProduct generated by hbm2java
 */
@Entity
@Table(name="buyer_buy_product"
    ,catalog="biddingschema"
)
public class BuyerBuyProduct  implements java.io.Serializable {


     private BuyerBuyProductId id;
     private float amount;
     private Date paymentDate;
     private int quantity;

    public BuyerBuyProduct() {
    }

    public BuyerBuyProduct(BuyerBuyProductId id, float amount, Date paymentDate, int quantity) {
       this.id = id;
       this.amount = amount;
       this.paymentDate = paymentDate;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="buyerId", column=@Column(name="buyer_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public BuyerBuyProductId getId() {
        return this.id;
    }
    
    public void setId(BuyerBuyProductId id) {
        this.id = id;
    }

    
    @Column(name="amount", nullable=false, precision=12, scale=0)
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false, length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


