package dao;// default package
// Generated Mar 20, 2021, 11:48:12 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="biddingschema"
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Date expirationDate;
     private Date finishDate;
     private Date manufacturingDate;
     private String manufacturingName;
     private String name;
     private Date offeredDate;
     private int quantity;
     private Integer sellerId;

    public Product() {
    }

	
    public Product(Date finishDate, Date manufacturingDate, String manufacturingName, String name, Date offeredDate, int quantity) {
        this.finishDate = finishDate;
        this.manufacturingDate = manufacturingDate;
        this.manufacturingName = manufacturingName;
        this.name = name;
        this.offeredDate = offeredDate;
        this.quantity = quantity;
    }
    public Product(String description, Date expirationDate, Date finishDate, Date manufacturingDate, String manufacturingName, String name, Date offeredDate, int quantity, Integer sellerId) {
       this.description = description;
       this.expirationDate = expirationDate;
       this.finishDate = finishDate;
       this.manufacturingDate = manufacturingDate;
       this.manufacturingName = manufacturingName;
       this.name = name;
       this.offeredDate = offeredDate;
       this.quantity = quantity;
       this.sellerId = sellerId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expiration_date", length=10)
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="finish_date", nullable=false, length=10)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="manufacturing_date", nullable=false, length=10)
    public Date getManufacturingDate() {
        return this.manufacturingDate;
    }
    
    public void setManufacturingDate(Date manufacturingDate) {
        this.manufacturingDate = manufacturingDate;
    }

    
    @Column(name="manufacturing_name", nullable=false, length=100)
    public String getManufacturingName() {
        return this.manufacturingName;
    }
    
    public void setManufacturingName(String manufacturingName) {
        this.manufacturingName = manufacturingName;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="offered_date", nullable=false, length=10)
    public Date getOfferedDate() {
        return this.offeredDate;
    }
    
    public void setOfferedDate(Date offeredDate) {
        this.offeredDate = offeredDate;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="seller_id")
    public Integer getSellerId() {
        return this.sellerId;
    }
    
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }




}


