package dao;// default package
// Generated Mar 20, 2021, 11:48:12 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductHasCategory generated by hbm2java
 */
@Entity
@Table(name="product_has_category"
    ,catalog="biddingschema"
)
public class ProductHasCategory  implements java.io.Serializable {


     private ProductHasCategoryId id;

    public ProductHasCategory() {
    }

    public ProductHasCategory(ProductHasCategoryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="categoryId", column=@Column(name="category_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public ProductHasCategoryId getId() {
        return this.id;
    }
    
    public void setId(ProductHasCategoryId id) {
        this.id = id;
    }




}


