package dao;// default package
// Generated Mar 20, 2021, 11:48:12 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductHasCategoryId generated by hbm2java
 */
@Embeddable
public class ProductHasCategoryId  implements java.io.Serializable {


     private int categoryId;
     private int productId;

    public ProductHasCategoryId() {
    }

    public ProductHasCategoryId(int categoryId, int productId) {
       this.categoryId = categoryId;
       this.productId = productId;
    }
   


    @Column(name="category_id", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductHasCategoryId) ) return false;
		 ProductHasCategoryId castOther = ( ProductHasCategoryId ) other; 
         
		 return (this.getCategoryId()==castOther.getCategoryId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCategoryId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


